### ISSUE TITLE
Reduce need for qualified imports

### ISSUE THREAD

**Issue by aspidites** [tfausak/purescript-batteries#1]
I wonder if something like [aspidites/cons](https://github.com/aspidites/cons/blob/master/src/Cons.purs) would be useful in generalizing some of the overloaded functions. 

In my quick experiments, for instance, I'm able to have a `delete` function that works with lists and sequences (getting weird errors when trying to write an array instance, for some reason), and thus would no longer need to import the respective modules qualified. Ideally, if this is a reasonable approach, Batteries would just re-export delete from Cons (which i'll move somewhere more suitable once I'm sure this is even a good idea).

**Comment by tfausak** [comment]
I would love this! When I put this together, I got frustrated at the need for qualified imports. Abstracting over the containers with a type class sounds like a good way to reduce the need for that. 

I think some existing type classes already cover some of the functionality. For example, `Unfoldable` provides `singleton`, which is defined by no fewer than 7 containers.

**Comment by aspidites** [comment]
Cool. Do you happen to know if there is something that does what Cons does already? In the mean time, I'll open a PR so we can monitor this.

**Comment by tfausak** [comment]
I don't know of any like Cons. For what it's worth, it reminds me of [`conj`](http://clojuredocs.org/clojure.core/conj) from Clojure.

**Comment by aspidites** [comment]
Actually, I think I found a way to do this without Cons. At least, in Haskell it works. I'm sorting through why the definition won't work in Purescript at the moment.

**Comment by aspidites** [comment]
Here's what I have so far:
```purescript
deleteBy :: forall f t a. (Applicative f, Foldable t, Monoid (f a))
         => (a -> a -> Boolean) -> a -> t a -> f a
deleteBy eq x =
  foldl (\acc c -> if x `eq` c then acc else acc <> pure c) mempty

delete :: forall f t a. (Eq a, Applicative f, Foldable t, Monoid (f a))
       => a -> t a -> f a
delete = deleteBy (==)
```

Using it, however, throws an error:
```
No instance found for
    Prelude.Applicative _5
```

Works fine in haskell though, given sufficient enough type annotations.

**Comment by tfausak** [comment]
I'm not sure what to make of that error.

Although I haven't stated it anywhere, my goal for this package is to not define anything in it. Instead I want to pull in other packages. So even if it is possible to define `delete` and friends without `Cons`, I'd prefer to have those definitions in a separate package. That way you can get them without pulling in all of Batteries.

**Comment by aspidites** [comment]
That makes sense. If I can ever figure that error out, I might start a package that has polymorphic versions of the array-like data types (sequence, array, list).

**Comment by tfausak** [comment]
I marked every colliding import with either a TODO or a NOTE in 0f85b2dd0e67ee082f46d0fb420a18b4cee04f15. That should give you an idea of how many functions there are shared among the container types.

**Comment by tfausak** [comment]
I got rid of Batteries' qualified imports in #9. Now if you want arrays, you have to import `Data.Array`. That doesn't really affect this issue, but it's good to know.

I also added more container types in #13. They implement most of the same functions.

**Comment by aspidites** [comment]
Awesome. Now when I have time to pick this back up, I know exactly where to pick up again.

**Comment by tfausak** [comment]
For what it's worth, the [purescript-filterable](https://github.com/michaelficarra/purescript-filterable) package includes a `Consable` type class

**Comment by aspidites** [comment]
Cool. That said, I needed append, not cons. Also, what was wrong with my function was that it couldn't infer types. I'm opening a PR that depends on a package that I'm calling purescript-containers for now. I'll consider it ready for merging once I've taken the time to write documentation and add the other functions that can reasonably be generalized.

**Comment by aspidites** [comment]
Update: Turns out my implementation was more akin to a filter (as it removed all occurrences of an element, rather than simply the first. As such, the Consable type class *would*  be necessary. 

That said, I've been doing some thinking, and I'm wondering if using polymorphic functions would really be a good idea. That is, if we do, the compiled javascript would be passed an instance dictionary, so the implementation would be slower than the monomorphic versions. I'm wondering if a better approach would be to import all three hiding the clashing names from the least prominent data type implementations. Since Array is a primitive type, it would seem like a good candidate. The user would then import the other libraries qualified if they wanted the List or Sequence specific variants, optionally hiding the Array variants instead if they are dealing with the same data structure consistently. 

The other alternative would be to have a top-level module for each data type which imported the base set of imports plus the type-specific ones. This is only subtly different from what your initial implementation had when you announced this library. Instead of:

```purescript
import Batteries
import Batteries.Array
```

You would have
```purescript
Import Batteries.Array
```

Which implies the `import Batteries`. The benefit of this over my last suggestion is that which data type takes precedence is made explicit, which could reduce confusion or the need to look up documentation.

What do you think, @tfausak? @paf31, can you comment on if my assessment about polymorphic functions is correct?

**Comment by tfausak** [comment]
I think having an array-based prelude would be convenient right up until you needed both array and maps, at which point it would be frustrating. Even though you could do something like this, why are arrays more important than maps? 

``` purescript
import Batteries.Array
import qualified Data.Map as M
```

But I feel like you're almost always going to want strings (which aren't containers per se, but have many of the same functions), arrays, and (string) maps. I'm fine with others (sequences, sets, catenable lists, etc.) requiring special imports.

**Comment by aspidites** [comment]
Hmm..maybe your curate exports ticket solves the "spirit" of this ticket? I'm comfortable with it being closed in that regard.

**Comment by tfausak** [comment]
Even with a curated export list (#16), there are going to be functions that you want to work on multiple containers.

**Comment by tfausak** [comment]
This isn't something that can really be solved by Batteries. Making generalized functions the work on many containers is outside the scope of this project. I will gladly add any packages that do that, but as far as I know there aren't any.
