### ISSUE TITLE
Curate export list

### ISSUE THREAD

**Issue by tfausak** [tfausak/purescript-batteries#16]
Currently my strategy is to export anything that doesn't conflict with any other modules I'm exporting. That's not great, as I noted here: https://github.com/tfausak/purescript-batteries/pull/15#discussion_r42891749. I should make a pass through the exports and make sure they all make sense to export.

**Comment by tfausak** [comment]
As part of this, I would like to document the exports. First pass could list them. Next pass could add types. Next pass could add links to the package they came from. And so on...

That sounds like a lot of work, though. And potentially hard to keep in sync. So I'll keep it in mind and open another issue when I want to do that.

**Comment by tfausak** [comment]
This could take a while, Batteries exports over 1,000 things.

**Comment by aspidites** [comment]
If you split up the different passes into tickets, I'd be willing to tackle some of it while you do others. For instance, once you've figured out what to export from Data.List, I could go back through and add links or whatever that you wanted (given there is an example of what you want accomplished first).

**Comment by tfausak** [comment]
I added a raw list of exports in c8bebbca3c7932a1aa7da4020e78312db45cd6b0. I think adding types might be unnecessary, since you can search by name or type on Pursuit. Also if the docs link to where the function came from, that place will have the type. So I think adding links is really all I want to do with regards to documentation. I'll make an issue for that.

**Comment by aspidites** [comment]
Even with the performance considerations I mentioned, or am I just imagining things? That is, in Haskell, I'd be 100% for polymorphic functions, but since that gets compiled down to a manually passed around instance dict, I'd be nervous. If you're convinced that worrying about performance is premature, I'll continue the work I was later this week (buried under school work and real work).

**Comment by tfausak** [comment]
I'd rather have slow, convenient functions that fast, cumbersome ones. If you're using a polymorphic function and recognize that it's slowing you down, you can easily switch it for the monomorphic version.

**Comment by aspidites** [comment]
Perhaps raising that caveat would be good for new comers. Something like "note: While polymorphic functions are more convenient than their monomorphic variants, they are slower. If you find that your application is experiencing considerable slow downs, a quick way to improve performance is to switch to the monomorphic variants where necessary."

Actually, if people are typing their functions, specializing them at the call site should be sufficient enough to avoid the performance penalty, right? Not sure why that didn't occur to me, assuming I'm correct!

**Comment by tfausak** [comment]
> raising that caveat would be good for new comers

Agreed. Although probably not really necessary until this package hits 1.0. 

> specializing them at the call site should be sufficient enough to avoid the performance penalty

That's definitely worth investigating. I have no idea.

**Comment by aspidites** [comment]
I was wrong about the specializing stuff :-(

**Comment by tfausak** [comment]
I am not planning on addressing this anymore. Batteries will continue to export everything it can. If you want a curated export list, you can depend on Batteries and make your own prelude.

**Comment by aspidites** [comment]
> make your own prelude

Sounds fair. Simple enough as well.

On Fri, Jan 29, 2016 at 2:54 PM, Taylor Fausak <notifications@github.com>
wrote:

> Closed #16 <https://github.com/tfausak/purescript-batteries/issues/16>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tfausak/purescript-batteries/issues/16#event-531827197>
> .
>



-- 
Regards,
Edwin O Marshall (aspidites)
http://github.com/aspidites <https://github.com/aspidites>
http://bitbucket.org/aspidites <https://bitbucket.org/aspidites>
http://www.assembla.com/profile/aspidites?public=true
