### ISSUE TITLE
Conflicts with 1.0.x libs

### ISSUE THREAD

**Issue by texastoland** [tfausak/purescript-batteries#28]
I `--force-latest`ed after `purescript-generics`, `purescript-integers`, `purescript-random`.

**Comment by tfausak** [comment]
Yeah I haven't updated this in a while. Last time I tried, there was still one holdout. I think it was [sequences](https://github.com/hdgarrood/purescript-sequences).

**Comment by texastoland** [comment]
It still is but I'm finishing a PR without it.

**Comment by texastoland** [comment]
Just uncomment it when it's fixed?

**Comment by tfausak** [comment]
Commenting it out would be a breaking change. I guess since I'm pre-1.0.0 I can still do whatever I want though.

**Comment by texastoland** [comment]
I think just `0.6`? Also do you have any automated process or all by hand?
