### ISSUE TITLE
Update Data.Int exports

### ISSUE THREAD

**Issue by texastoland** [tfausak/purescript-batteries#30]
I noticed `toStringAs` and `radix` missing.

**Comment by tfausak** [comment]
Looks like I'm missing a few exports.

Export | Included?
--- | ---
fromNumber | yes
floor | yes
ceil | yes
round | yes
toNumber | yes
fromString | no
even | yes
odd | yes
Radix | no
binary | no
octal | no
decimal | no
hexadecimal | no
radix | no
fromStringAs | no
toStringAs | no

I think they could all be added except `fromString`.

**Comment by texastoland** [comment]
I'm fighting the urge to start automation rather than go through this for every library 😉

**Comment by tfausak** [comment]
Automating this might be easier than auditing it by hand. I've been thinking about how I want to approach it, but I don't have any solid ideas yet.

**Comment by texastoland** [comment]
Let's brainstorm before Hacked and I'll help. I think it'd make the biggest user facing impact of anything I want to work on.

**Comment by texastoland** [comment]
I missed `Data.Time.Duration` last time too.

**Comment by texastoland** [comment]
Closing in favor of #31. Working on my last project this was only one of several (I didn't count) modules I missed.
